# Last release of the tf-runner image
# https://github.com/flux-iac/tf-runner-images/pkgs/container/tf-runner
FROM ghcr.io/flux-iac/tf-runner:main-00031bcc@sha256:0a58ffb95144fdf738a4c925b4accfc312c4953b3c4dbf02677001ceb8453b88

ARG TARGETARCH=amd64
ARG TF_VERSION=1.8.1

# Switch to root to have permissions for operations
USER root

ADD https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_${TARGETARCH}.zip /terraform_${TF_VERSION}_linux_${TARGETARCH}.zip

# Overwrite the existing terraform binary
RUN unzip -o -q /terraform_${TF_VERSION}_linux_${TARGETARCH}.zip -d /usr/local/bin/ && \
    rm /terraform_${TF_VERSION}_linux_${TARGETARCH}.zip &&  \
    chmod +x /usr/local/bin/terraform

# Switch back to the non-root user after operations
USER 65532:65532
